version: '3.7'

services:

  web:
    stdin_open: true
    container_name: webapp_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
